services:
  mariadb:
    container_name: mariadb
    networks:
    - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on:
    - wordpress
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    env_file: .env
    expose:
    - "9000"
    restart: on-failure
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/pibernar/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/pibernar/data/mariadb'
networks:
  inception:
    driver: bridge
